### ISSUE TITLE
Is there a C# version of the code?

### ISSUE THREAD

**Issue by AhmadKelany** [SallaApp/ZATCA#1]
Thanks for the code to help developers get up-to-speed with the requirements,

Is there a way to use it in a .Net desktop environment?

If not, could you please point me to the right direction to meet the requirements in a .Net desktop application?

**Comment by salkhwlani** [comment]
Hi @AhmadKelany ,

We write an article to example how you can implement it with any language

salla.dev/blog/qr-code-fatoora-e-invoicing-zatca
