### ISSUE TITLE
SALLA/ZATCA PHP minimum version  is 7.4 

### ISSUE THREAD

**Issue by ARemaity** [SallaApp/ZATCA#11]
i was trying to implement the package with 7.3.x  php version , based on the documentation it support 7.2> but unfortunately im getting error with composer :

chillerlan/php-qrcode[4.3.0, ..., 4.3.2] require php ^7.4 || ^8.0 -> your php version (7.3.28) does not satisfy that requirement.
    - Root composer.json requires chillerlan/php-qrcode ^4.3 -> satisfiable by chillerlan/php-qrcode[4.3]

is there version that support lower version?

**Comment by salkhwlani** [comment]
@ARemaity we updatesd the composer.json to support the old version of QR code package, you can give it try 

https://github.com/SallaApp/ZATCA/releases/tag/2.0.1

**Comment by ARemaity** [comment]
thank you for the support
