### ISSUE TITLE
Qr code not readable in VAT app

### ISSUE THREAD

**Issue by osamatoama** [SallaApp/ZATCA#17]
when I try to read the QR code at https://play.google.com/store/apps/details?id=com.zatca.vat it shows that the invoice is not registered while the all invoices at salla merchants are readable and show registered at the the ap

**Comment by salkhwlani** [comment]
@osamatoama share with us the QR code here

**Comment by osamatoama** [comment]
the code 
$qr = GenerateQrCode::fromArray([
            new Seller(config('zatca.seller_number')),
            new TaxNumber(config('zatca.tax_number')),
            new InvoiceDate($order->created_at),
            new InvoiceTotalAmount($ztotal),
            new InvoiceTaxAmount($ztotal - ($ztotal / 1.15)),
        ])->render();
        
        the QR code 
        
![image](https://user-images.githubusercontent.com/16557402/157015585-60d8c19d-cfd1-4869-b558-1586ca481489.png)

the vat result 

![image](https://user-images.githubusercontent.com/16557402/157015809-f670722f-41c6-423b-b78d-716de57e7cb2.png)

**Comment by osamatoama** [comment]
any response?

**Comment by osamatoama** [comment]
dear, 

please check the same invoice with this app https://play.google.com/store/apps/details?id=com.zatca.vat it shows that the invoice is not registered while I have a store on sale and all the invoices are registered

**Comment by JoDeveloper** [comment]
same issue with me ?!
