### ISSUE TITLE
.Net Version

### ISSUE THREAD

**Issue by TobieFehlaber** [SallaApp/ZATCA#2]
Hi , is there any .NET version of this as asked previously ? Or any guidance will be appreciated

**Comment by salkhwlani** [comment]
Hi @TobieFehlaber, 

We write an article to example how you can implement it with any language 

https://salla.dev/blog/qr-code-fatoora-e-invoicing-zatca/

**Comment by TobieFehlaber** [comment]
Hi Salah ,

Thank you for the response. I will go through it.

Kind Regards,
Tobie

**Comment by Ishak-ali** [comment]
hi Tobie,

I found this it might be useful for you https://github.com/aljbri/Zatca.Net

**Comment by TobieFehlaber** [comment]
Hi ,

Thank you. I will look into it.

Kind Regards,
