### ISSUE TITLE
ZATCA phase 2 implementation

### ISSUE THREAD

**Issue by webappickhasan** [SallaApp/ZATCA#20]
How to implement ZATCA phase 2. Which is 
1. Generate an XML file
2. Send the invoice to the FATOORA portal for validation

**Comment by Gabriel-Grosu** [comment]
Yes, this would be awesome to have!

**Comment by ali-alharthi** [comment]
This library only helps to create a valid QR code.
The ZATCA phase 2 need an XML invoice according using UBL specifications while implementing EN 16931 Rules and KSA Rules. Also, it should be digitally signed. Therefore, this require a new big project to achieve that.

Keep in mind, there is a business for these solutions so most likely it would be paid and not free.

**Comment by webappickhasan** [comment]
Please mention the business name.
