### ISSUE TITLE
When you will create new example of e-invoicing phase 2

### ISSUE THREAD

**Issue by mosleh200989** [SallaApp/ZATCA#23]
Please create new e-invoicing phase 2 example.

**Comment by salkhwlani** [comment]
We're working on it this month

**Comment by mohamedalaa80000** [comment]
I finished phase two integration all steps
Contact me i will provide all steps
On whatsapp 00201210407130

**Comment by nagibmahfuj** [comment]
> We're working on it this month

@salkhwlani  Any update?

**Comment by salkhwlani** [comment]
@mosleh200989 @nagibmahfuj @mohamedalaa80000

We are working to release is in the last week of this month; we are in verification step on the production with ZACAT

**Comment by nagibmahfuj** [comment]
Appreciate your work, if there is any update, let us know

**Comment by mohamedalaa80000** [comment]
I Already finished it @nagibmahfuj

**Comment by ahmedallamul** [comment]
@salkhwlani is the phase 2 on the generate-csr branch and will you merge it with the master branch soon ?

**Comment by mohamedalaa80000** [comment]
@ahmedallamul  contact with me i finished it
On whatsapp 00201210407130

**Comment by thaifanisalla** [comment]
> @salkhwlani is the phase 2 on the generate-csr branch and will you merge it with the master branch soon ?

Hi guys , We will merge it as soon this week .

**Comment by vivekudayan** [comment]
@thaifanisalla Any Update?

**Comment by mohamedalaa80000** [comment]
@thaifanisalla contact with me i finished it
On whatsapp 00201210407130

**Comment by nagibmahfuj** [comment]
@salkhwlani @thaifanisalla any progress update on phase 2?

**Comment by mohamedalaa80000** [comment]
@nagibmahfuj
contact with me i finished it
On whatsapp 00201210407130

**Comment by mohamedalaa80000** [comment]
If anyone need help and i have zatca phase 2 integration from onBoarding to send invoices
I can help on whatsapp: 00201210407130

**Comment by mohamedalaa80000** [comment]
I have full phase two integration with php

**Comment by twf-nikhila** [comment]
> I have full phase two integration with php

@mohamedalaa80000 please share or give details

**Comment by thaifanisalla** [comment]
Hi @mohamedalaa80000 
This package does limited things :
- generate qrCode for phase 1, 2 
- Generate CSR 
- Sign all xml invoice types which must generated by your provider system , the sign operation include (generate hash , signature dsign , signing steps)

**Comment by alexmigf** [comment]
Is there a deadline for this implementation?

**Comment by thaifanisalla** [comment]
Hi @mosleh200989 
Master now ready to use in Phase 2 implementation , there are an update in readme how to use it 

Feel free to inform us of any issue you face

**Comment by salkhwlani** [comment]
v3.0 released
