### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by malsmary** [SallaApp/ZATCA#3]
How i can use it in PHP Codeigniter

**Comment by malsmary** [comment]
Can you help me plz , by vedio

**Comment by naeem5364** [comment]
is there any code for c# .net

**Comment by salkhwlani** [comment]
@malsmary @naeem5364 

We write an article to example how you can implement it with any language

[salla.dev/blog/qr-code-fatoora-e-invoicing-zatca
](https://salla.dev/blog/qr-code-fatoora-e-invoicing-zatca/)

also we are available at </Salla Developers> for any support

**Comment by naeem5364** [comment]
We want to integrate ZATCA 2nd Phase QR? Using C# Sql Server Can you help us?
