### ISSUE TITLE
Standard invoice generation support

### ISSUE THREAD

**Issue by tabish1** [SallaApp/ZATCA#39]
I think only simplified tax invoice is supported yet, if that's not the case then can you please explain how to generate standard invoice xml?

**Comment by thaifanisalla** [comment]
Hi @tabish1 
please read this : https://github.com/SallaApp/ZATCA/issues/41#issuecomment-2495530147

**Comment by tabish1** [comment]
Do you have any plan to include that in the near future? @thaifanisalla

**Comment by thaifanisalla** [comment]
Hi @tabish1 

Nop, not in this package
