### ISSUE TITLE
i cann't load Certificate

### ISSUE THREAD

**Issue by mub009** [SallaApp/ZATCA#40]
phpseclib3\Exception\NoKeyLoadedException
Unable to read key

below i share 

$certificate = (new Certificate(
            base64_decode('TUlJQ1BUQ0NBZU9nQXdJQkFnSUdBWXp6Z0VoTk1Bb0dDQ3FHU000OUJBTUNNQlV4RXpBUkJnTlZCQU1NQ21WSmJuWnZhV05wYm1jd0hoY05NalF3TVRFd01UTXhNVFUwV2hjTk1qa3dNVEE1TWpFd01EQXdXakIxTVFzd0NRWURWUVFHRXdKVFFURVdNQlFHQTFVRUN3d05VbWw1WVdSb0lFSnlZVzVqYURFbU1DUUdBMVVFQ2d3ZFRXRjRhVzExYlNCVGNHVmxaQ0JVWldOb0lGTjFjSEJzZVNCTVZFUXhKakFrQmdOVkJBTU1IVlJUVkMwNE9EWTBNekV4TkRVdE16azVPVGs1T1RrNU9UQXdNREF6TUZZd0VBWUhLb1pJemowQ0FRWUZLNEVFQUFvRFFnQUVvV0NLYTBTYTlGSUVyVE92MHVBa0MxVklLWHhVOW5QcHgydmxmNHloTWVqeThjMDJYSmJsRHE3dFB5ZG84bXEwYWhPTW1Obzhnd25pN1h0MUtUOVVlS09Cd1RDQnZqQU1CZ05WSFJNQkFmOEVBakFBTUlHdEJnTlZIUkVFZ2FVd2dhS2tnWjh3Z1p3eE96QTVCZ05WQkFRTU1qRXRWRk5VZkRJdFZGTlVmRE10WldReU1tWXhaRGd0WlRaaE1pMHhNVEU0TFRsaU5UZ3RaRGxoT0dZeE1XVTBORFZtTVI4d0hRWUtDWkltaVpQeUxHUUJBUXdQTXprNU9UazVPVGs1T1RBd01EQXpNUTB3Q3dZRFZRUU1EQVF4TVRBd01SRXdEd1lEVlFRYURBaFNVbEpFTWpreU9URWFNQmdHQTFVRUR3d1JVM1Z3Y0d4NUlHRmpkR2wyYVhScFpYTXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSUY4akljeHp2Q3lxVURUcDVPbXY3MlVweFBBTG1vUnl0OURZMjRqV21CUUFpQTBiYVo2WXJwcDV5SjRhaG9vb1czK09hOGtrYjMxZXZBb0hkdmdEODA2M3c9PQ=='), // get from ZATCA when you exchange the CSR via APIs
            $generateCSR->getCsrContent() // generated at stage one
        ))->setSecretKey('Dehvg1fc8GF6Jwt5bOxXwC6enR93VxeNEo2mlUatfgw='); // get from ZATCA when you exchange the CSR via APIs
        $invoice = (new InvoiceSign($xml,$certificate))->sign();

**Comment by eng-ahmedtaher** [comment]
can you load Certificate  like this 

$certificate = (new Certificate(
            base64_decode($certificate), // Certificate Here
            $privateKey // PrivateKey Here
        ))->setSecretKey($secretKey); // Secret Key Here

        $invoice = (new InvoiceSign($xmlInvoice, $certificate))->sign();
        
        // invoice Hash: $invoice->getHash()
  // invoice signed as XML: $invoice->getInvoice()
  // Invoice QR code as base64: $invoice->getQRCode()

**Comment by mub009** [comment]
i tried this code but i got same error and attached image ..what i faced issue
![Capture](https://github.com/user-attachments/assets/6fbb1bf1-d088-47ca-b3fd-181a7d1c701d)

**Comment by mub009** [comment]
thanks solve this issue...private key not genarated

**Comment by mub009** [comment]
thanks solved this issue...private key not genarated

**Comment by EducoreAPK** [comment]
@mub009 How did you generate the private key then? its generating the certificate file but not the private key file
