### ISSUE TITLE
Can you share Tax invoice phase 2 full implementation example

### ISSUE THREAD

**Issue by bangashasif** [SallaApp/ZATCA#41]
Can you share Tax invoice phase 2 full implementation example.

i have laravel project, i already use salla/zatca for phase 1.  now i want to add code phase 2. can you help me in this

**Comment by thopr** [comment]
> Can you share Tax invoice phase 2 full implementation example.
> 
> i have laravel project, i already use salla/zatca for phase 1. now i want to add code phase 2. can you help me in this

hello, I'm in the same situation did you manage to figure it out , I'm stuck at sending the CSR to zatca to get the certificate and secret kay

**Comment by thaifanisalla** [comment]
Hi @bangashasif @thopr 
This package serve the following :

- Generating CSR
- Signing Invoices & Generate QA code
- Generating QR Code As Base64
- Generate Base64 (phase one)
- Generate Plain

More details in readme [here](https://github.com/SallaApp/ZATCA/blob/master/README.md).


so the implementation of generate xml invoice is out of scope this package
