### ISSUE TITLE
QR image generated displays base64 encoded data not the actual data

### ISSUE THREAD

**Issue by AbdelRahman-Elshafai** [SallaApp/ZATCA#6]
Hello, the qr image generated displays the base64 encoded data not the actual data?

i have used the code you provided to display it in an image tag

```
 $displayQRCodeAsBase64 = GenerateQrCode::fromArray([
                new Seller('Salla'), // seller name
                new TaxNumber('1234567891'),
                new InvoiceDate('2021-07-12T14:25:09Z'),
                new InvoiceTotalAmount('100.00'),
                new InvoiceTaxAmount('15.00')
])->render();

<img src="<?php echo $displayQRCodeAsBase64;?>" alt="QR Code" />
```
this is the qr code generated by the code above you can scan it and see for yourself

https://ibb.co/3cMjybb

am i missing something?

**Comment by salkhwlani** [comment]
@AbdelRahman-Elshafai we will check..

**Comment by salkhwlani** [comment]
@AbdelRahman-Elshafai The QR is not readable btw, so it's okay some QR readers doesn't recognize the output for the human eyes, 

If you want to test the output you can use the Phone QR Reader, or the following website 

https://www.onlinebarcodereader.com/


This is a example for the output of your QR Code

![eDWbslfj-2021-11-18 at 09 27 09](https://user-images.githubusercontent.com/10876587/142363793-03f4d6e0-9ff8-4931-9438-62db5bf46416.png)

**Comment by AbdelRahman-Elshafai** [comment]
yes that's exactly what i mean the content is the base64 encoded data not the actual data that i submitted.

isn't it supposed to show me the seller name ex: 'Salla' not the base64 encoded data?

**Comment by ali-alharthi** [comment]
@AbdelRahman-Elshafai It should be encoded in base64. 
"It is mandatory to generate and print QR code encoded in Base64 format with up to 500 char-
acters" as stated by ZATCA.
Please read the [QRCodeCreation](https://zatca.gov.sa/ar/E-Invoicing/SystemsDevelopers/Documents/QRCodeCreation.pdf).
